### ISSUE TITLE
Error on first launch after following install instructions

### ISSUE THREAD

**Issue by EnragedAntelope** [discus0434/comfyui-flux-accelerator#2]
Hi, thank you for making this.

I receive this error on first launch of Comfyui after installing and following directions. I am on windows 11, python 3.11.9, cuda 12.4:
```
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\comfyui-flux-accelerator\__init__.py", line 6, in <module>
    from torchao.quantization import float8_weight_only, int8_weight_only, quantize_
ImportError: cannot import name 'float8_weight_only' from 'torchao.quantization' (D:\ComfyUI\venv\Lib\site-packages\torchao\quantization\__init__.py)

Cannot import D:\ComfyUI\custom_nodes\comfyui-flux-accelerator module for custom nodes: cannot import name 'float8_weight_only' from 'torchao.quantization' (D:\ComfyUI\venv\Lib\site-packages\torchao\quantization\__init__.py)
```

Pip list output:
Package                                  Version
---------------------------------------- ------------------
absl-py                                  2.1.0
accelerate                               0.34.2
addict                                   2.4.0
aenum                                    3.1.15
aggdraw                                  1.3.18.post0
aiohappyeyeballs                         2.4.0
aiohttp                                  3.10.5
aiohttp-sse                              2.2.0
aioresponses                             0.7.6
aiosignal                                1.3.1
albucore                                 0.0.16
albumentations                           1.4.15
altair                                   5.4.1
annotated-types                          0.7.0
anthropic                                0.34.2
antlr4-python3-runtime                   4.9.3
anyio                                    4.4.0
APScheduler                              3.10.1
argostranslate                           1.9.6
arrow                                    1.3.0
asgiref                                  3.8.1
asttokens                                2.4.1
attrs                                    24.2.0
auto_gptq                                0.7.1
av                                       13.0.0
awscli                                   1.33.44
babel                                    2.16.0
backcall                                 0.2.0
backoff                                  2.2.1
bcrypt                                   4.2.0
beautifulsoup4                           4.12.3
binaryornot                              0.4.4
bitsandbytes                             0.43.3
bleach                                   6.1.0
blend_modes                              2.1.0
blendmodes                               2024.1.1
blind-watermark                          0.4.4
boto3                                    1.34.123
botocore                                 1.34.162
Brotli                                   1.1.0
build                                    1.2.2
cachetools                               5.5.0
came-pytorch                             0.1.3
certifi                                  2024.8.30
cffi                                     1.17.1
chardet                                  5.2.0
charloratools                            1.0.0
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.6
chromadb                                 0.5.5
click                                    8.1.7
clip                                     1.0
clip-interrogator                        0.6.0
cmake                                    3.30.3
color-matcher                            0.5.0
colorama                                 0.4.4
coloredlogs                              15.0.1
colorlog                                 6.8.2
colour                                   0.1.5
colour-science                           0.4.4
compel                                   2.0.3
contourpy                                1.3.0
cookiecutter                             2.6.0
cryptography                             43.0.1
cssselect2                               0.7.0
cstr                                     0.1.0
ctranslate2                              4.3.1
cycler                                   0.12.1
Cython                                   3.0.0
dataclasses-json                         0.6.7
datasets                                 3.0.0
ddt                                      1.7.2
decorator                                4.4.2
deep-translator                          1.11.4
deepdiff                                 8.0.1
defusedxml                               0.7.1
Deprecated                               1.2.14
diffusers                                0.30.3
dill                                     0.3.8
diskcache                                5.6.3
distro                                   1.9.0
docker                                   6.1.3
docker-pycreds                           0.4.0
docopt                                   0.6.2
docstring_parser                         0.16
docutils                                 0.16
dynamicprompts                           0.31.0
easydict                                 1.13
einops                                   0.8.0
eval_type_backport                       0.2.0
evalidate                                2.0.3
executing                                2.1.0
facexlib                                 0.3.0
fairscale                                0.4.0
fastapi                                  0.110.3
fastjsonschema                           2.20.0
ffmpy                                    0.3.0
filelock                                 3.16.1
filterpy                                 1.4.5
fire                                     0.6.0
flash_attn                               2.6.3
flatbuffers                              24.3.25
flet                                     0.24.1
flet-core                                0.24.1
flet-runtime                             0.24.1
fonttools                                4.53.1
frozenlist                               1.4.1
fsspec                                   2024.9.0
ftfy                                     6.2.3
fvcore                                   0.1.5.post20221221
gdown                                    5.2.0
gekko                                    1.2.1
gguf                                     0.10.0
ghp-import                               2.1.0
gitdb                                    4.0.11
GitPython                                3.1.43
glitch_this                              1.0.3
google-ai-generativelanguage             0.6.6
google-api-core                          2.19.2
google-api-python-client                 2.144.0
google-auth                              2.34.0
google-auth-httplib2                     0.2.0
google-cloud-core                        2.4.1
google-cloud-storage                     2.18.2
google-crc32c                            1.6.0
google-generativeai                      0.7.2
google-resumable-media                   2.7.2
googleapis-common-protos                 1.65.0
googletrans-py                           4.0.0
GPUtil                                   1.4.0
griffe                                   1.2.0
groq                                     0.11.0
grpcio                                   1.66.1
grpcio-status                            1.62.3
h11                                      0.14.0
h2                                       4.1.0
hpack                                    4.0.0
httpcore                                 1.0.5
httplib2                                 0.22.0
httptools                                0.6.1
httpx                                    0.27.2
huggingface-hub                          0.25.0
humanfriendly                            10.0
hydra-core                               1.3.2
hyperframe                               6.0.1
idna                                     3.10
ImageHash                                4.3.1
imageio                                  2.35.1
imageio-ffmpeg                           0.5.1
imagesize                                1.4.1
img2texture                              1.0.6
importlib_metadata                       8.5.0
importlib_resources                      6.4.4
inference-cli                            0.18.1
inference-gpu                            0.18.1
iniconfig                                2.0.0
insightface                              0.7.3
iopath                                   0.1.10
ipdb                                     0.13.13
ipython                                  8.12.3
jax                                      0.4.31
jaxlib                                   0.4.31
jedi                                     0.19.1
Jinja2                                   3.1.4
jiter                                    0.5.0
jmespath                                 1.0.1
joblib                                   1.4.2
json_repair                              0.29.1
jsonschema                               4.23.0
jsonschema-specifications                2023.12.1
jupyter_client                           8.6.2
jupyter_core                             5.7.2
jupyterlab_pygments                      0.3.0
kiwisolver                               1.4.7
kornia                                   0.7.3
kornia_rs                                0.1.5
kubernetes                               30.1.0
lark-parser                              0.12.0
lazy_loader                              0.4
lightning                                2.4.0
lightning-utilities                      0.11.7
lion-pytorch                             0.2.2
llama-cpp-agent                          0.0.17
llama_cpp_python                         0.2.90
llvmlite                                 0.43.0
loguru                                   0.7.2
lxml                                     5.3.0
Mako                                     1.3.5
manifold3d                               2.5.1
mapbox_earcut                            1.0.2
Markdown                                 3.7
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.22.0
matplotlib                               3.9.2
matplotlib-inline                        0.1.7
matrix-client                            0.4.0
mdurl                                    0.1.2
mediapipe                                0.10.14
mergedeep                                1.3.4
mistune                                  3.0.2
mkdocs                                   1.6.1
mkdocs-autorefs                          1.2.0
mkdocs-get-deps                          0.2.0
mkdocs-material                          9.5.34
mkdocs-material-extensions               1.3.1
mkdocstrings                             0.26.1
mkdocstrings-python                      1.11.1
ml-dtypes                                0.4.0
mmh3                                     4.1.0
monotonic                                1.6
moviepy                                  1.0.3
mpmath                                   1.3.0
mss                                      9.0.2
multidict                                6.1.0
multiprocess                             0.70.16
mutagen                                  1.47.0
mypy-extensions                          1.0.0
narwhals                                 1.6.4
nbclient                                 0.10.0
nbconvert                                7.16.4
nbformat                                 5.10.4
networkx                                 3.3
ninja                                    1.11.1.1
numba                                    0.60.0
numpy                                    1.26.4
oauthlib                                 3.2.2
ollama                                   0.3.2
omegaconf                                2.3.0
onnx                                     1.16.2
onnxruntime                              1.19.2
onnxruntime-gpu                          1.15.1
open_clip_torch                          2.26.1
openai                                   1.44.0
openai-clip                              1.0.1
opencv-contrib-python                    4.10.0.84
opencv-python                            4.10.0.84
opencv-python-headless                   4.10.0.84
opentelemetry-api                        1.27.0
opentelemetry-exporter-otlp-proto-common 1.27.0
opentelemetry-exporter-otlp-proto-grpc   1.27.0
opentelemetry-instrumentation            0.48b0
opentelemetry-instrumentation-asgi       0.48b0
opentelemetry-instrumentation-fastapi    0.48b0
opentelemetry-proto                      1.27.0
opentelemetry-sdk                        1.27.0
opentelemetry-semantic-conventions       0.48b0
opentelemetry-util-http                  0.48b0
opt-einsum                               3.3.0
orderly-set                              5.2.2
orjson                                   3.10.7
outcome                                  1.3.0.post0
overrides                                7.7.0
packaging                                24.1
paginate                                 0.5.7
pandas                                   2.2.2
pandocfilters                            1.5.1
parso                                    0.8.4
pathspec                                 0.12.1
pefile                                   2024.8.26
peft                                     0.12.0
pendulum                                 3.0.0
pickleshare                              0.7.5
piexif                                   1.1.3
pilgram                                  1.2.1
pillow                                   10.4.0
pillow-avif-plugin                       1.4.6
pip                                      24.2
pipreqs                                  0.5.0
pixeloe                                  0.0.10
pixelsort                                1.0.1
platformdirs                             4.3.2
pluggy                                   1.5.0
pooch                                    1.8.2
portalocker                              2.10.1
posthog                                  3.6.3
prettytable                              3.11.0
prodigyopt                               1.0
proglog                                  0.1.10
prometheus_client                        0.20.0
prometheus-fastapi-instrumentator        6.0.0
prompt_toolkit                           3.0.47
proto-plus                               1.24.0
protobuf                                 4.25.4
psd-tools                                1.9.34
psutil                                   6.0.0
PuLP                                     2.9.0
pure_eval                                0.2.3
py-cpuinfo                               3.3.0
pyarrow                                  17.0.0
pyasn1                                   0.6.0
pyasn1_modules                           0.4.0
pyav                                     13.0.0
pybase64                                 1.4.0
pybind11                                 2.13.6
pycocoevalcap                            1.2
pycocotools                              2.0.8
pycollada                                0.8
pycparser                                2.22
pycryptodomex                            3.20.0
pycuda                                   2024.1.2
pydantic                                 2.9.2
pydantic_core                            2.23.4
pydantic-settings                        2.4.0
pydot                                    3.0.1
pyexiv2                                  2.14.0
pygame                                   2.6.0
PyGithub                                 2.4.0
Pygments                                 2.18.0
PyJWT                                    2.9.0
pykalman                                 0.9.7
PyMatting                                1.1.12
pymdown-extensions                       10.9
PyNaCl                                   1.5.0
pynvml                                   11.5.3
pyOpenSSL                                24.2.1
pyparsing                                3.1.4
PyPika                                   0.48.9
pypng                                    0.20220715.0
pyproject_hooks                          1.1.0
pyreadline3                              3.4.1
pySmartDL                                1.3.4
PySocks                                  1.7.1
pytest                                   8.3.2
pytest-asyncio                           0.21.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-slugify                           8.0.4
pytools                                  2024.1.14
pytorch-lightning                        2.4.0
pytz                                     2024.2
PyWavelets                               1.7.0
pywin32                                  306
PyYAML                                   6.0.2
pyyaml_env_tag                           0.1
pyzbar                                   0.1.9
pyzmq                                    26.2.0
qrcode                                   7.4.2
redis                                    5.0.8
referencing                              0.35.1
regex                                    2024.9.11
rembg                                    2.0.59
repath                                   0.9.0
reportlab                                4.2.2
requests                                 2.31.0
requests-file                            2.1.0
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
requirements-parser                      0.11.0
rf-clip                                  1.1
rich                                     13.5.2
rich-argparse                            1.5.2
rouge                                    1.0.1
rpds-py                                  0.20.0
rsa                                      4.7.2
Rtree                                    1.3.0
s3transfer                               0.10.2
sacremoses                               0.0.53
safetensors                              0.4.5
scenedetect                              0.6.4
schedulefree                             1.2.7
scikit-build                             0.18.1
scikit-image                             0.24.0
scikit-learn                             1.5.1
scipy                                    1.14.1
seaborn                                  0.13.2
segment-anything                         1.0
selenium                                 4.24.0
sentencepiece                            0.2.0
sentry-sdk                               2.14.0
setproctitle                             1.3.3
setuptools                               72.1.0
shapely                                  2.0.6
shellingham                              1.5.4
simpleeval                               0.9.13
six                                      1.16.0
skypilot                                 0.5.0
smmap                                    5.0.1
sniffio                                  1.3.1
sortedcontainers                         2.4.0
sounddevice                              0.5.0
soundfile                                0.12.1
soupsieve                                2.6
spandrel                                 0.3.4
stack-data                               0.6.3
stanza                                   1.1.1
starlette                                0.37.2
structlog                                24.4.0
supervision                              0.22.0
svg.path                                 6.3
svglib                                   1.5.1
sympy                                    1.13.3
symusic                                  0.5.2
tabulate                                 0.9.0
tenacity                                 9.0.0
termcolor                                2.4.0
text-unidecode                           1.3
threadpoolctl                            3.5.0
tifffile                                 2024.8.30
time-machine                             2.15.0
timm                                     0.6.13
tinycss2                                 1.3.0
tldextract                               5.1.2
tokenizers                               0.19.1
toml                                     0.10.2
tomli                                    2.0.1
torch                                    2.4.1+cu124
torchao                                  0.1
torchaudio                               2.4.1
torchdiffeq                              0.2.4
torchmetrics                             1.4.2
torchscale                               0.3.0
torchsde                                 0.2.6
torchvision                              0.19.1+cu124
tornado                                  6.4.1
tqdm                                     4.66.5
traitlets                                5.14.3
trampoline                               0.1.2
transformers                             4.44.2
transparent-background                   1.3.2
trimesh                                  4.4.9
trio                                     0.26.2
trio-websocket                           0.11.1
triton                                   2.1.0
typer                                    0.9.0
typer-config                             1.4.0
types-python-dateutil                    2.9.0.20240906
types-setuptools                         74.1.0.20240907
typing                                   3.7.4.3
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.1
tzlocal                                  5.2
ultralytics                              8.2.89
ultralytics-thop                         2.0.6
uritemplate                              4.1.1
urllib3                                  1.26.20
uv                                       0.4.13
uvicorn                                  0.30.6
vhacdx                                   0.0.8.post1
voluptuous                               0.15.2
vtracer                                  0.6.11
wandb                                    0.17.9
watchdog                                 4.0.2
watchfiles                               0.24.0
wcwidth                                  0.2.13
webdriver-manager                        4.0.2
webencodings                             0.5.1
websocket-client                         1.8.0
websockets                               13.0.1
wget                                     3.2
wheel                                    0.44.0
win32-setctime                           1.1.0
wordcloud                                1.9.3
wrapt                                    1.16.0
wsproto                                  1.2.0
xatlas                                   0.0.9
xformers                                 0.0.28.post1
xxhash                                   3.5.0
yacs                                     0.1.8
yapf                                     0.40.2
yarg                                     0.1.9
yarl                                     1.11.1
yt-dlp                                   2024.8.6
zipp                                     3.20.2
zxing-cpp                                2.2.0

**Comment by StartHua** [comment]
me too

**Comment by demiguelm** [comment]
Linux only right?

**Comment by discus0434** [comment]
It seems torchao version is incorrect. I'm gonna check the installation command later

**Comment by Apacchi88** [comment]
> This node currently does not work on Windows because 2 core acceleration methods are incompatible with it: torchao and torch.compile(). I would like to handle it, but it will be difficult.

Could you indicate on the install page that this is for Linux only please, I wasted some time copying and pasting commands and browsing through threads just to find out it doesn't work for Windows😅
