### ISSUE TITLE
Working in Windows

### ISSUE THREAD

**Issue by jepjoo** [discus0434/comfyui-flux-accelerator#8]
Installed Triton from here:
https://github.com/woct0rdho/triton-windows

Then installed torchao 0.5.0 from source. Node works in Windows now.

**Comment by RYG81** [comment]
how to install torchao 0.5.0?
torchao-0.1 is getting installed

**Comment by RYG81** [comment]
OK. All the best to resolve this issue.

**Comment by Donzox** [comment]
> I actually had some weird issues with CogVideo when torchao 0.5.0 was installed with 2.4.1. Today I updated both, to 0.6.1 and 2.5.0 respectively and the weird issue is gone.
> 
> To install torchao from source I did this (in ComfyUI_windows_portable folder) git clone -b release/0.6.1 https://github.com/pytorch/ao.git cd ao ..\python_embeded\python.exe setup.py build ..\python_embeded\python.exe setup.py install
> 
> Build was failing with sparse_marlin but this fixed it: [pytorch/ao#951](https://github.com/pytorch/ao/issues/951)
> 
> edit: Actually, the node isn't working now... it did with ao 0.5.0 and torch 2.4.1 yesterday. My current torchao installation might be broken or something.
> 
> "mm_dit_skip_blocks" works but "do_compile" does not.
> 
> Error when compile enabled:
> !!! Exception during processing !!! __self__ mismatch for bound method
> 
> from user code: File "G:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\flux\model.py", line 159, in forward out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control)
> 
> Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
> 
> You can suppress this exception and fall back to eager by setting: import torch._dynamo torch._dynamo.config.suppress_errors = True
> 
I'm also seeing that error on linux and windows.

`!!! Exception during processing !!! __self__ mismatch for bound method `

**Comment by frankyifei** [comment]
not working and same error, maybe this is a pytorch version mismatch, I am on torch 2.5.1, not nightly

**Comment by Apacchi88** [comment]
> I actually had some weird issues with CogVideo when torchao 0.5.0 was installed with 2.4.1. Today I updated both, to 0.6.1 and 2.5.0 respectively and the weird issue is gone.
> 
> To install torchao from source I did this (in ComfyUI_windows_portable folder) git clone -b release/0.6.1 https://github.com/pytorch/ao.git cd ao ..\python_embeded\python.exe setup.py build ..\python_embeded\python.exe setup.py install
> 
> Build was failing with sparse_marlin but this fixed it: [pytorch/ao#951](https://github.com/pytorch/ao/issues/951)
> 
> edit: Actually, the node isn't working now... it did with ao 0.5.0 and torch 2.4.1 yesterday. My current torchao installation might be broken or something.
> 
> "mm_dit_skip_blocks" works but "do_compile" does not.
> 
> Error when compile enabled:

Did you manage to find a fix?

**Comment by Piscabo** [comment]
> 

Me too, Windows does not have the newer version? I get this error:
_Traceback (most recent call last):
  File "E:\AI_Files\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI_Files\ComfyUI\custom_nodes\comfyui-flux-accelerator\__init__.py", line 6, in <module>
    from torchao.quantization import float8_weight_only, int8_weight_only, quantize_
ImportError: cannot import name 'float8_weight_only' from 'torchao.quantization' (E:\AI_Files\venv\Lib\site-packages\torchao\quantization\__init__.py)

Cannot import E:\AI_Files\ComfyUI\custom_nodes\comfyui-flux-accelerator module for custom nodes: cannot import name 'float8_weight_only' from 'torchao.quantization' (E:\AI_Files\venv\Lib\site-packages\torchao\quantization\__init__.py)_

**Comment by Piscabo** [comment]
> > 
> 
> Me too, Windows does not have the newer version? I get this error: _Traceback (most recent call last): File "E:\AI_Files\ComfyUI\nodes.py", line 2037, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\AI_Files\ComfyUI\custom_nodes\comfyui-flux-accelerator__init__.py", line 6, in from torchao.quantization import float8_weight_only, int8_weight_only, quantize_ ImportError: cannot import name 'float8_weight_only' from 'torchao.quantization' (E:\AI_Files\venv\Lib\site-packages\torchao\quantization__init__.py)
> 
> Cannot import E:\AI_Files\ComfyUI\custom_nodes\comfyui-flux-accelerator module for custom nodes: cannot import name 'float8_weight_only' from 'torchao.quantization' (E:\AI_Files\venv\Lib\site-packages\torchao\quantization__init__.py)_

It was fixed when I installed this version into the VENV: (recently released)
pip install torchao==0.7.0

**Comment by Maxxxel** [comment]
@Piscabo Can you explain your whole installation settings to make it work on windows?

**Comment by Maxxxel** [comment]
> > I actually had some weird issues with CogVideo when torchao 0.5.0 was installed with 2.4.1. Today I updated both, to 0.6.1 and 2.5.0 respectively and the weird issue is gone.
> > To install torchao from source I did this (in ComfyUI_windows_portable folder) git clone -b release/0.6.1 https://github.com/pytorch/ao.git cd ao ..\python_embeded\python.exe setup.py build ..\python_embeded\python.exe setup.py install
> > Build was failing with sparse_marlin but this fixed it: [pytorch/ao#951](https://github.com/pytorch/ao/issues/951)
> > edit: Actually, the node isn't working now... it did with ao 0.5.0 and torch 2.4.1 yesterday. My current torchao installation might be broken or something.
> > "mm_dit_skip_blocks" works but "do_compile" does not.
> > Error when compile enabled:
> 
> Did you manage to find a fix?

also have the same error

**Comment by Piscabo** [comment]
> @Piscabo Can you explain your whole installation settings to make it work on windows?

I deleted this, as does not work for my GPU 3060RTX 12GB
