### ISSUE TITLE
issue after installing manually the missing torchao

### ISSUE THREAD

**Issue by Nico53425342** [discus0434/comfyui-flux-accelerator#9]
File "C:\Users\Admin\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-flux-accelerator\__init__.py", line 6, in <module>
    from torchao.quantization import float8_weight_only, int8_weight_only, quantize_
ImportError: cannot import name 'float8_weight_only' from 'torchao.quantization' (C:\Users\Admin\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchao\quantization\__init__.py)

Cannot import C:\Users\Admin\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-flux-accelerator module for custom nodes: cannot import name 'float8_weight_only' from 'torchao.quantization' (C:\Users\Admin\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchao\quantization\__init__.py)

**Comment by Maelstrom2014** [comment]
the same:
`Traceback (most recent call last):
  File "C:\ai\comfyui\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ai\comfyui\ComfyUI\custom_nodes\comfyui-flux-accelerator\__init__.py", line 6, in <module>
    from torchao.quantization import float8_weight_only, int8_weight_only, quantize_
ImportError: cannot import name 'float8_weight_only' from 'torchao.quantization' (C:\ai\comfyui\python_embeded\Lib\site-packages\torchao\quantization\__init__.py)`
